// ============================================================
//  MAXIMUM CARNAGE DEMAKE - GBC
//  music.c  -  Music playback via GBT Player (tracker format)
//  sfx.c merged here for simplicity
//
//  In a real build:
//  - Music data lives in res/music/*.c (exported from hUGETracker
//    or GBT Player .mod format)
//  - GBT Player library handles frame-by-frame register writes
//    to CH1-CH4 (Square 1, Square 2, Wave, Noise)
//  - SFX are short sequences that temporarily override a channel
// ============================================================

#include "main.h"

// ============================================================
//  TRACK IDs
// ============================================================
#define TRACK_DOWNTOWN      0   // energetic city beat
#define TRACK_ROOFTOPS      1   // driving action theme
#define TRACK_SEWERS        2   // dark, tense atmosphere
#define TRACK_WAREHOUSE     3   // industrial pulse
#define TRACK_RAVENCROFT    4   // creepy, unsettling
#define TRACK_CARNAGE_LAIR  5   // chaotic boss lead-up
#define TRACK_CUTSCENE      20  // ambient story music
#define TRACK_TITLE         30  // main title theme
#define TRACK_CHAR_SELECT   31  // short character select loop
#define TRACK_BOSS          32  // intense boss fight music
#define TRACK_GAMEOVER      33  // somber game over
#define TRACK_CREDITS       34  // victory/ending theme
#define TRACK_CARNAGE_BOSS  35  // Carnage campaign final boss

// ============================================================
//  SFX IDs
// ============================================================
#define SFX_PLAYER_HURT     0
#define SFX_WEB_SHOOT       1
#define SFX_WEB_SWING       2
#define SFX_CARNAGE_RAGE    3
#define SFX_VENOM_WHIP      4
#define SFX_TENDRIL_BURST   5
#define SFX_JUMP            6
#define SFX_PUNCH           7
#define SFX_ENEMY_HURT      8
#define SFX_ENEMY_DEATH     9
#define SFX_BOSS_DEATH      10
#define SFX_BOSS_PHASE      11
#define SFX_TEXT_BLIP       12
#define SFX_CURSOR_MOVE     13
#define SFX_CONFIRM         14

// ============================================================
//  GBT PLAYER INTEGRATION STUBS
//  Replace these stubs with real GBT Player calls:
//    gbt_play(music_data[track_id], GBT_SPEED_NORMAL);
//    gbt_update(); // called every VBlank
//    gbt_stop();
// ============================================================

static uint8_t current_track = 0xFF;
static uint8_t music_playing  = 0;

// Extern declarations for song data arrays
// (These would be generated by hUGETracker or GBT Player)
// extern const uint8_t song_downtown[];
// extern const uint8_t song_rooftops[];
// ... etc.

// Placeholder song table
static const void * const SONG_TABLE[] = {
    NULL, // 0  downtown
    NULL, // 1  rooftops
    NULL, // 2  sewers
    NULL, // 3  warehouse
    NULL, // 4  ravencroft
    NULL, // 5  carnage lair
    NULL, NULL, NULL, NULL, // 6-9
    NULL, NULL, NULL, NULL, NULL, // 10-14
    NULL, NULL, NULL, NULL, NULL, // 15-19
    NULL, // 20 cutscene
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, // 21-29
    NULL, // 30 title
    NULL, // 31 char select
    NULL, // 32 boss
    NULL, // 33 gameover
    NULL, // 34 credits
    NULL, // 35 carnage boss
};
#define SONG_TABLE_SIZE (sizeof(SONG_TABLE)/sizeof(SONG_TABLE[0]))

void music_init(void) {
    current_track = 0xFF;
    music_playing  = 0;
    // gbt_init();  // Initialize GBT Player
}

void music_play(uint8_t track_id) {
    if (track_id == current_track) return; // already playing
    if (track_id >= SONG_TABLE_SIZE) return;

    current_track = track_id;
    music_playing  = 1;

    // Real call: gbt_play(SONG_TABLE[track_id], GBT_SPEED_NORMAL);
    // gbt_loop(1);  // loop music
}

void music_stop(void) {
    music_playing = 0;
    current_track = 0xFF;
    // gbt_stop();
}

void music_update(void) {
    if (!music_playing) return;
    // gbt_update();  // must be called every VBlank / frame
}

// ============================================================
//  SFX  - Simple duty-cycle square wave pulses on CH1
//  In a real build, these would be short tracker patterns that
//  temporarily take over CH1 or CH4 (noise)
// ============================================================

// SFX register writes:
// NR10 = sweep, NR11 = duty/length, NR12 = envelope,
// NR13/NR14 = frequency + trigger

typedef struct {
    uint8_t nr10;  // sweep
    uint8_t nr11;  // duty | length
    uint8_t nr12;  // envelope
    uint8_t nr13;  // freq lo
    uint8_t nr14;  // freq hi | trigger
} SFXDef;

static const SFXDef SFX_TABLE[] = {
    // SFX_PLAYER_HURT: low descending noise
    {0x00, 0x80, 0xF0, 0x80, 0xC7},
    // SFX_WEB_SHOOT: rising chirp
    {0x75, 0x40, 0xA2, 0x20, 0xC6},
    // SFX_WEB_SWING: whoosh (ch2 duty sweep)
    {0x00, 0x40, 0x72, 0x40, 0xC6},
    // SFX_CARNAGE_RAGE: distorted growl (noise)
    {0x00, 0xFF, 0xF3, 0x00, 0xC7},
    // SFX_VENOM_WHIP: heavy thwack
    {0x00, 0xC0, 0xE2, 0x60, 0xC5},
    // SFX_TENDRIL_BURST: multi-hit burst
    {0x00, 0xFF, 0xD2, 0x10, 0xC7},
    // SFX_JUMP: short upward blip
    {0x56, 0x40, 0xA0, 0x40, 0xC5},
    // SFX_PUNCH: sharp hit
    {0x00, 0xFF, 0xF0, 0x00, 0xC0},
    // SFX_ENEMY_HURT: enemy yelp
    {0x00, 0x80, 0xB1, 0xA0, 0xC6},
    // SFX_ENEMY_DEATH: descending tone
    {0x1F, 0xC0, 0xC0, 0x00, 0xC7},
    // SFX_BOSS_DEATH: big explosion noise
    {0x00, 0xFF, 0xF2, 0x00, 0xCF},
    // SFX_BOSS_PHASE: alarm beep
    {0x00, 0x40, 0xF0, 0x00, 0xC3},
    // SFX_TEXT_BLIP: tiny chirp
    {0x00, 0xC0, 0x51, 0xC0, 0xC5},
    // SFX_CURSOR_MOVE: soft click
    {0x00, 0x40, 0x31, 0x00, 0xC4},
    // SFX_CONFIRM: rising 2-note
    {0x34, 0x40, 0xA0, 0x80, 0xC6},
};

void sfx_play(uint8_t sfx_id) {
    if (sfx_id >= (sizeof(SFX_TABLE) / sizeof(SFX_TABLE[0]))) return;
    const SFXDef *s = &SFX_TABLE[sfx_id];

    // Write directly to GBC sound registers
    // These work on real hardware and in emulators
    NR10_REG = s->nr10;
    NR11_REG = s->nr11;
    NR12_REG = s->nr12;
    NR13_REG = s->nr13;
    NR14_REG = s->nr14;
}
